// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI-powered tool to automatically generate daily attendance reports from work logs and uploaded timestamped pictures.
 *
 * - generateAttendanceReport - A function that handles the attendance report generation process.
 * - GenerateAttendanceReportInput - The input type for the generateAttendanceReport function.
 * - GenerateAttendanceReportOutput - The return type for the generateAttendanceReport function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAttendanceReportInputSchema = z.object({
  workLogs: z
    .string()
    .describe('A detailed work log including laborer names, work descriptions, and locations.'),
  timestampedPictures: z
    .string()
    .describe(
      'Timestamped images for verification, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.' 
    ),
});

export type GenerateAttendanceReportInput = z.infer<
  typeof GenerateAttendanceReportInputSchema
>;

const GenerateAttendanceReportOutputSchema = z.object({
  report: z.string().describe('The generated daily attendance report.'),
});

export type GenerateAttendanceReportOutput = z.infer<
  typeof GenerateAttendanceReportOutputSchema
>;

export async function generateAttendanceReport(
  input: GenerateAttendanceReportInput
): Promise<GenerateAttendanceReportOutput> {
  return generateAttendanceReportFlow(input);
}

const generateAttendanceReportPrompt = ai.definePrompt({
  name: 'generateAttendanceReportPrompt',
  input: {schema: GenerateAttendanceReportInputSchema},
  output: {schema: GenerateAttendanceReportOutputSchema},
  prompt: `You are an AI assistant that generates daily attendance reports based on work logs and timestamped pictures.

  Work Logs: {{{workLogs}}}
  Timestamped Pictures: {{media url=timestampedPictures}}

  Based on the provided information, generate a comprehensive daily attendance report, ensuring to verify labor presence and activities.
  The report must be in markdown format.
  `,
});

const generateAttendanceReportFlow = ai.defineFlow(
  {
    name: 'generateAttendanceReportFlow',
    inputSchema: GenerateAttendanceReportInputSchema,
    outputSchema: GenerateAttendanceReportOutputSchema,
  },
  async input => {
    const {output} = await generateAttendanceReportPrompt(input);
    return output!;
  }
);
