
"use client";

import React, { useState, useEffect, lazy, Suspense, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { PlusCircle, UserCircle2, Loader2, FileText } from 'lucide-react';
import { DataTable } from '@/components/common/data-table';
import type { Labour } from '@/lib/types';
// import { initialLabours } from '@/lib/data'; // No longer used for initialization here
import { useToast } from "@/hooks/use-toast";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
// import { LABOURS_STORAGE_KEY } from '@/lib/storageKeys'; // No longer using localStorage directly here
// import useDebouncedLocalStorage from '@/hooks/useDebouncedLocalStorage'; // No longer using this hook here
import { getAllLabours, addLabour, updateLabour, deleteLabourById } from '@/lib/labour-actions';
import { uploadLabourPhoto } from '@/lib/actions'; // For photo uploads to Vercel Blob

const LabourForm = lazy(() => import('@/components/labours/labour-form').then(module => ({ default: module.LabourForm })));

export default function LaboursPage() {
  const [labours, setLabours] = useState<Labour[]>([]);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingLabour, setEditingLabour] = useState<Labour | undefined>(undefined);
  const [isLoadingData, setIsLoadingData] = useState(true);
  const { toast } = useToast();

  const fetchLabours = useCallback(async () => {
    setIsLoadingData(true);
    try {
      const serverLabours = await getAllLabours();
      setLabours(serverLabours);
    } catch (error) {
      console.error("Failed to fetch labours:", error);
      toast({
        title: "Error",
        description: "Could not load labours from the server.",
        variant: "destructive",
      });
    } finally {
      setIsLoadingData(false);
    }
  }, [toast]);

  useEffect(() => {
    fetchLabours();
    if (typeof window !== "undefined" && window.location.hash === "#add") {
      setIsFormOpen(true);
      window.location.hash = ""; 
    }
  }, [fetchLabours]);

  const handleAddLabour = useCallback(() => {
    setEditingLabour(undefined);
    setIsFormOpen(true);
  }, []);

  const handleEditLabour = useCallback((labour: Labour) => {
    setEditingLabour(labour);
    setIsFormOpen(true);
  }, []);

  const handleDeleteLabour = useCallback(async (labourToDelete: Labour) => {
    try {
      await deleteLabourById(labourToDelete.id);
      setLabours(prevLabours => prevLabours.filter(l => l.id !== labourToDelete.id));
      toast({
        title: "Labour Deleted",
        description: `${labourToDelete.name} has been removed.`,
        variant: "destructive",
      });
    } catch (error) {
      console.error("Failed to delete labour:", error);
      toast({
        title: "Error Deleting Labour",
        description: "Could not delete labour. Please try again.",
        variant: "destructive",
      });
    }
  }, [toast]);

  const handleFormSubmit = useCallback(async (submittedLabourData: Labour) => {
    // Photo upload is handled within LabourForm which calls uploadLabourPhoto server action
    // and passes the photoUrl in submittedLabourData.
    // File fields like photoFile, aadhaarFile etc. are not part of the Labour type stored on server.
    const { photoFile, aadhaarFile, panFile, licenseFile, ...storableLabourData } = submittedLabourData;

    try {
      if (editingLabour) {
        const updated = await updateLabour(storableLabourData);
        setLabours(prevLabours => prevLabours.map(l => l.id === updated.id ? updated : l));
        toast({ title: "Labour Updated", description: `${updated.name}'s details have been updated.` });
      } else {
        // For addLabour, we pass data excluding 'id' as it's generated by the action.
        // Also, file objects are not passed to server action for adding, only their URLs/previews after upload.
        const { id, ...dataForAdd } = storableLabourData; 
        const newLabour = await addLabour(dataForAdd);
        setLabours(prevLabours => [newLabour, ...prevLabours]);
        toast({ title: "Labour Added", description: `${newLabour.name} has been added.` });
      }
      setIsFormOpen(false);
      setEditingLabour(undefined);
    } catch (error) {
      console.error("Failed to save labour:", error);
      toast({
        title: "Error Saving Labour",
        description: "Could not save labour details. Please try again.",
        variant: "destructive",
      });
    }
  }, [editingLabour, toast]);

  const columns = React.useMemo(() => [
    { 
      accessorKey: 'photoUrl' as keyof Labour,
      header: 'Photo',
      cell: (item: Labour) => (
        <Avatar className="h-10 w-10">
          <AvatarImage src={item.photoUrl} alt={item.name} data-ai-hint="person portrait" />
          <AvatarFallback>
            <UserCircle2 className="h-6 w-6 text-muted-foreground" />
          </AvatarFallback>
        </Avatar>
      )
    },
    { accessorKey: 'name' as keyof Labour, header: 'Name' },
    { accessorKey: 'details' as keyof Labour, header: 'Details' },
    { 
      accessorKey: 'salaryRate' as keyof Labour, 
      header: 'Daily Rate (₹)', 
      cell: (item: Labour) => item.salaryRate ? `₹${item.salaryRate.toFixed(2)}` : '-' 
    },
    { 
      accessorKey: 'phoneNo' as keyof Labour, 
      header: 'Phone No.', 
      cell: (item: Labour) => item.phoneNo || '-' 
    },
    { 
      accessorKey: 'emergencyPhoneNo' as keyof Labour, 
      header: 'Emergency No.', 
      cell: (item: Labour) => item.emergencyPhoneNo || '-' 
    },
    { accessorKey: 'aadhaarNo' as keyof Labour, header: 'Aadhaar No.', cell: (item: Labour) => item.aadhaarNo || '-' },
    { accessorKey: 'panNo' as keyof Labour, header: 'PAN No.', cell: (item: Labour) => item.panNo || '-' },
    {
      header: 'Docs',
      cell: (item: Labour) => (
        <div className="flex space-x-1">
          {[
            { preview: item.aadhaarPreview, name: "Aadhaar" },
            { preview: item.panPreview, name: "PAN" },
            { preview: item.licensePreview, name: "License" },
          ].map(doc => doc.preview && (
            <TooltipProvider key={doc.name} delayDuration={100}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <span className="cursor-default">
                    <FileText className="h-4 w-4 text-muted-foreground hover:text-primary" />
                  </span>
                </TooltipTrigger>
                <TooltipContent>
                  <p>{doc.name} uploaded (preview only)</p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          ))}
        </div>
      )
    }
  ], []);

  if (isLoadingData) {
    return (
      <div className="container mx-auto py-8 flex justify-center items-center">
        <Loader2 className="h-10 w-10 animate-spin text-primary" />
        <span className="ml-2">Loading labours...</span>
      </div>
    );
  }

  return (
    <div className="container mx-auto py-8">
      <div className="flex flex-col items-start sm:flex-row sm:justify-between sm:items-center gap-4 mb-8">
        <h1 className="text-3xl font-bold text-foreground">Labour Management</h1>
        <Button 
          onClick={handleAddLabour} 
          className="w-full sm:w-auto bg-primary hover:bg-primary/90 text-primary-foreground self-stretch sm:self-auto"
        >
          <PlusCircle className="mr-2 h-5 w-5" /> Add Labour
        </Button>
      </div>

      <DataTable
        columns={columns}
        data={labours}
        onEdit={handleEditLabour}
        onDelete={handleDeleteLabour}
      />

      {isFormOpen && (
        <Suspense fallback={
          <div className="fixed inset-0 bg-background/30 backdrop-blur-sm flex items-center justify-center z-[60]">
            <div className="bg-card p-6 rounded-lg shadow-xl flex items-center space-x-2">
              <Loader2 className="h-5 w-5 animate-spin text-primary" />
              <span>Loading Form...</span>
            </div>
          </div>
        }>
          <LabourForm
            isOpen={isFormOpen}
            onClose={() => {
              setIsFormOpen(false);
              setEditingLabour(undefined);
            }}
            onSubmit={handleFormSubmit}
            defaultValues={editingLabour}
          />
        </Suspense>
      )}
    </div>
  );
}
